name: Android CI
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2.3.3
      - name: Setup JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.0
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
